version: '3.8'

# ###########################################################
# Docker Compose para EIBELSTORE
# ###########################################################

services:
  # Tu aplicación Node.js
  app:
    build: .
    container_name: ecomerce_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_USER=usuario_ecom
      - DB_PASSWORD=password_seguro
      - DB_NAME=eibelstore_db
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - db

  # La base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: ecomerce_db
    environment:
      - POSTGRES_USER=usuario_ecom
      - POSTGRES_PASSWORD=password_seguro
      - POSTGRES_DB=eibelstore_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/init.sql

  # Servidor Nginx (Proxy y Frontend)
  nginx:
    image: nginx:alpine
    container_name: ecomerce_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/usr/share/nginx/html:ro
    depends_on:
      - app

# Definimos los volúmenes para persistir la información.
volumes:
  postgres_data:
